
- HomeLab Production:
    - Home Assistant:
        - href: http://192.168.178.238:8123
          icon: home-assistant.png
    - NodeRed HA:
        - href: http://192.168.178.238:1885
          icon: node-red.png
    - DSMR:
        - href: http://192.168.178.248:7777
          icon: https://github.com/dsmrreader/dsmr-reader/blob/v5/dsmr_frontend/static/dsmr_frontend/img/favicons/favicon-32x32.png?raw=true
    - Zigbee:
        - href: http://192.168.178.91
          icon: phoscon-light.png
    - Z-wave JS:
        - href: http://192.168.178.101:8091
          icon: z-wave-js-ui.png
    - ESPhome:
        - href: http://192.168.178.127:6052
          icon: esphome.png

          

- HomeLab Testing:
    - Home Assistant:
        - href: http://192.168.178.78:8123
          icon: home-assistant.png
    - NodeRed:
        - href: http://192.168.178.160:1880
          icon: node-red.png
    - N8N:
        - href: http://192.168.178.165
          icon: n8n.png


- Services:
    - Nextcloud:
        - href: https://nextcloud.ztormstiql.nl
          icon: nextcloud.png
    - Immich:
        - href: https://fotos.hasz.app
          icon: immich.png
    - Plex:
        - href: http://192.168.178.238:32400
          icon: plex.png
    - Jellyfin:
        - href: http://192.168.178.238:8096
          icon: jellyfin.png
    - Sonarr:
        - href: http://192.168.178.238:8989
          icon: sonarr.png
    - Radarr:
        - href: http://192.168.178.238:7878
          icon: radarr.png      
    - Prowlarr:
        - href: http://192.168.178.238:9696
          icon: prowlarr.png
    - Bazarr:
        - href: http://192.168.178.238:6767
          icon: bazarr.png
    - NZBget:
        - href: http://192.168.178.238:6789
          icon: nzbget.png
    - Ombi:
        - href: http://192.168.178.238:3579
          icon: ombi.png
    - Zerobyte:
        - href: http://192.168.178.127:4096
          icon: zerobyte.png
    - Linkding:
        - href: https://links.hasz.app
          icon: linkding.png
