- Info:
    - AdGuard 1:
        href: http://192.168.178.234:1201
        icon: adguard-home.png
        widget:
          type: adguard
          url: http://192.168.178.234:1201
          username: ztorm
          password: Superbink1982!
    - AdGuard 2:
        href: http://192.168.178.101:1201
        icon: adguard-home.png
        widget:
          type: adguard
          url: http://192.168.178.101:1201
          username: ztorm
          password: Superbink1982!
    - Komodo:
        href: http://192.168.178.11:9120
        icon: komodo.png
        widget:
          type: komodo
          url: http://192.168.178.11:9120
          key: K-WHCPTC4YBkkL54uZE5D6v3Bf0x5lkPTHbQxTVziK
          secret: S-R3qNO12ehOqbbGjsqYEtTqImrmiDhgwmIg1FRvco
          showSummary: true # optional, default: false
          # showStacks: true # optional, default: false

    - Cup:
        href: http://192.168.178.127:8008
        icon: cup.png
        widget:
          type: customapi
          url: http://192.168.178.127:8008/api/v3/json
          refreshInterval: 10000
          method: GET
          mappings:
            - field: metrics.monitored_images
              label: Monitored images
              format: number
            - field: metrics.up_to_date
              label: Up to date
              format: number
            - field: metrics.updates_available
              label: Available updates
              format: number
    - Unifi:
        href: https://192.168.178.1
        icon: unifi.png
        widget:
          type: unifi
          url: https:/192.168.178.1
          key: Y3ANOQZSkQSaYUKGUyQfPhRoiOU2g1M_

    - NPM (.nl):
        href: http://192.168.178.29:81
        icon: nginx-proxy-manager.png
        widget:
          type: npm
          url: http://192.168.178.29:81
          username: ztormstiql@yahoo.com
          password: Superbink1982!
    - NPM (.app):
        href: http://192.168.178.168:81
        icon: nginx-proxy-manager.png
        widget:
          type: npm
          url: http://192.168.178.168:81
          username: ztormstiql@yahoo.com
          password: Superbink1982!

- Servers:
    - Proxmox:
        href: https://192.168.178.50:8006
        icon: proxmox.png 
    - Unraid:
        href: http://192.168.178.238
        icon: unraid.png
    - CasaOS:
        href: http://192.168.178.234
        icon: casaos.png
- Docker:
    - Server 1:
        href: https://192.168.178.101:9443
        icon: docker-moby.png
    - Server 2:
        href: https://192.168.178.127:9443
        icon: docker-moby.png
    - Server 3:
        href: https://192.168.178.29:9443
        icon: docker-moby.png

