background:
  image: /images/background.jpeg
  # opacity: 50

cardBlur: xl

bookmarksStyle: icons

layout:
  Info:
    style: row
    columns: 4
  HomeLab Production: 
  Servers:
    style: row
    columns: 4
  Docker:
    style: row
    columns: 4
